pipeline:
  build:
    image: golang
    commands:
      - go build
  docker:
    image: plugins/docker
    registry: ikr.iij.jp
    repo: ikr.iij.jp/keisuk-t/drone-test
    tags: latest
    volumes:
      - /etc/docker/certs.d:/etc/docker/certs.d
